AWSTemplateFormatVersion: '2010-09-09'
Description: 'Complete example of infrastructure setup'

Parameters:
  Environment:
    Type: String
    Default: dev
    Description: Environment name
    AllowedValues:
      - dev
      - staging
      - prod
  
  BucketPrefix:
    Type: String
    Default: my-company
    Description: Prefix for bucket names

Resources:
  StorageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${BucketPrefix}-${Environment}-storage
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Managed
          Value: cloudformation

  LockTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${BucketPrefix}-${Environment}-lock
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: LockID
          AttributeType: S
      KeySchema:
        - AttributeName: LockID
          KeyType: HASH
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Managed
          Value: cloudformation

Outputs:
  BucketName:
    Description: Name of the created S3 bucket
    Value: !Ref StorageBucket
  
  TableName:
    Description: Name of the created DynamoDB table
    Value: !Ref LockTable